# .github/workflows/sbom.yml
name: Generate CycloneDX SBOM

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-sbom:
    runs-on: ubuntu-latest

    # Needed for GitHub’s dependency-submission API later
    permissions:
      contents: read
      id-token: write

    steps:
      # Grab the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python the same way PyGoat runs
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'          # match runtime
          cache: pip

      # Install project deps & the OWASP SBOM generator
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install cyclonedx-bom            # OWASP-maintained CLI  [oai_citation:0‡PyPI](https://pypi.org/project/cyclonedx-bom/)

      # Build the CycloneDX SBOM (JSON)
      - name: Generate SBOM
        run: |
          cyclonedx-py requirements --output-file sbom.cdx.json

      # -------------- STORAGE / DISTRIBUTION OPTIONS --------------

      # Give engineers something to download
      - name: Upload as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: pygoat-sbom
          path: sbom.cdx.json
          retention-days: 30      # tunable

      # (optional) Push straight into OWASP Dependency-Track
      #       Only runs when you add the two secrets.
      - name: Upload to Dependency-Track
        if: ${{ secrets.DT_API_KEY != '' && secrets.DT_HOST != '' }}
        uses: DependencyTrack/gh-upload-sbom@v3          # official DT action 
        with:
          serverHostname: ${{ secrets.DT_HOST }}
          apiKey:         ${{ secrets.DT_API_KEY }}
          projectName:    ${{ github.event.repository.name }}
          projectVersion: ${{ github.sha }}
          bomFile:        sbom.cdx.json

      # Feed/patch GitHub’s own dependency graph
      #      (GitHub only accepts SPDX → convert first, then submit)
      - name: Install CycloneDX CLI (for format conversion)
        run: |
          curl -Lo cyclonedx https://github.com/CycloneDX/cyclonedx-cli/releases/latest/download/cyclonedx-linux-x64
          chmod +x cyclonedx && sudo mv cyclonedx /usr/local/bin

      - name: Convert CycloneDX → SPDX-JSON 2.2
        run: cyclonedx convert \
                --input-file sbom.cdx.json --input-format cyclonedx+json \
                --output-file sbom.spdx.json --output-format spdx+json   # 

      - name: Submit SPDX to the dependency graph
        uses: advanced-security/spdx-dependency-submission-action@v0.1.1 
        with:
          filePath: sbom.spdx.json
